### ISSUE TITLE
Complete initial Setup for Project

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/restaurant#10]
Setup all dependencies, libraries, settings.py and insert into README (Epic - README #9)

## TASKS

- [x] Django and Libraries installed
- [x] ElephantSQL and Cloudinary installed
- [x] Heroku App linked up
- [x] All Keys hidden in env.py
- [x] DataBase hidden
- [x] Test initial Deployment
- [x] Push all changes to Git
