### ISSUE TITLE
USER STORY: View Menu

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/restaurant#11]
As a **Site User** I can **view the Restaurants Menu** so that **I can see what food they offer**

## ACCEPTANCE CRITERIA 

- Site must have a menu section to navigate to
- Site Must be able to display the menu in a clear format
- Site must offer different dishes

## TASKS

- [x] Create HTML pages with navigation to a menu section
- [x] Add a Model in Django App for Menu
- [x] Add a Menu that can be displayed to users
