### ISSUE TITLE
USER STORY: Reserve a table

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/restaurant#12]
As a **Customer** I can **make  reservations** so that **I can book a table in the restaurant**

## ACCEPTANCE CRITERIA 

- Have a Booking section to make reservations
- Have a Booking form for booking details
- Have a booking Model to store form
- Have bookings stored in a Database

## TASKS

- [x] Create a booking section on the HTML and Style with CSS
- [x] Make a booking Database in Django 
- [x] Style forms with Crispy Forms 
- [x] Link the booking form to Reservation model in Django
- [x] Verify bookings are accepted
