### ISSUE TITLE
USER STORY: Display Webpage

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/restaurant#14]
As a **Site Admin** I can **display information about my restaurant** so that **customers can view it**

## ACCEPTANCE CRITERIA 

- Be able to display Home Page, About, Menu sections
- Have the site navigable to users/customers

## TASKS

- [x] Create basic HTML for Website
- [x] Give basic Style for the pages 
- [x] Have the site navigable/ insert links to different sections
