### ISSUE TITLE
TASK: Create a visible form that links to created Database Model

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/restaurant#16]
Create a form and have the data submitted stored database created

## ACCEPTANCE CRITERIA 

- Form is visible to users in HTML
- Form displays all the correct fields
- Form is Submittible
-  Form is saved to the created database

## TASKS

- [x] Create forms.py and link to created model
- [x] Create HTML page for form
- [x] Display form on HTML page
- [x] Link form to Model for form
- [x] Test form submission stores the form
