### ISSUE TITLE
TASK: Create a User Login

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/restaurant#17]
As a **User** I can **Regsiter/Login** so that **my information is stored**

## ACCEPTANCE CRITERIA 

- User is able to Login to Website
- User information is saved to Database
- User Information is retrievable from Database

## TASKS

- [ ] Create a Sign/Up login page
- [ ] Create a User Model (Similiar to Reservation Details model)
- [ ] Check information is stored in Database
