### ISSUE TITLE
USER STORY: Manage Bookings

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/restaurant#20]
As a **Site Owner** I can **manage bookings** so that **the restaurant does not exceed capacity**

## ACCEPTANCE CRITERIA 

- Have a Capacity set for the restaurant
- Have a duration for each booking
- Ensure that bookings can't exceed capacity
- Ensure new bookings don't lead to overlapping over-capacity
- Show customer if capacity exceeded at their booking period

## TASKS

- [x] Set a Capacity limit 
- [x] Set a Booking Duration
- [x] Test Capacity and show error if exceeded
- [x]  Test Duration in conjunction with capacity
- [x]  Test Capacity for duration of bookings
- [x]  Write Function to check capacity for duration of booking
- [x]  Display Validation Error display if capacity exceeded
-
