### ISSUE TITLE
BUG: MESSAGES NOT DISPLAYING

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/restaurant#21]
Django messages not displaying on Login/ Signup/ Lougout

## ACCEPTANCE CRITERIA 

- Messages display when User Login
- Messages display when User Logout 
- Messages display when User SignUp
- Error Messages Display

## TASKS

- [x] Import check - from django.contrib.messages import constants as messages
- [x] Check Settings.py 
- [x] check views.py for errors
- [x] Check base.html and signup.html

## FIXES

- [x] Import of login meant name change needed for login function in view
- [x] URLS needed updating after login function name change
- [x] Styling in base.html to display messages above block content
