### ISSUE TITLE
STYLING : CREATE CUSTOM MODALS

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/restaurant#23]
HAVE CUSTOM MODALS APPEAR FOR USER TO CONFIRM BOOKINGS AND SHOW FORM ERRORS

## ACCEPTANCE CRITERIA 

- CUSTOM MODAL APPEARS ASKING USER TO CONFIRM BOOKING
- MODAL SHOWS BOOKING INFORMATION
- MODAL STYLED AND FORMATTED
- MODAL LINKS WORK CORRECTLY

## TASKS

- [x] CREATE CUSTOM MODAL TEMPLATE
- [x] TEST TEMPLATE DISPLAING CORRECTLY
- [x] FORMAT MODAL TEMPLATE TO INCLUDE BOOKING
- [x] TEST FORMATTED MODAL
- [x] TEST MODAL LINKS WORK CORRECTLY
- [x] STYLE MODAL

## BUGS
- [x] Time not displaying in Modal

## FIXES
- [x] Set time to check input:checked as it is a RadioTag
