### ISSUE TITLE
TASK: USE CUSTOM MODAL FOR DELETION

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/restaurant#24]
Incorporate the Custom Modal in the delete reservation function instead of having two modals

## ACCEPTANCE CRITERIA 

- Have Delete Reservation call the customModal
- In the ShowModal: reword to ask if Deletion confirmed
- Remove unneeded HTML 
- Reword Scripts in base.html
- Rename JS files

## TASKS

- [x] Link JS to renamed JS file
- [x] Rewrite JS to call the customModal 
- [x] Test Modal is displaying
- [x] Rewrite the content of the Modal
- [x] Test Modal links working
- [x] Test Delete Function working

## BUGS

- [x] Click not doing anything once modal displayed

## FIXES

- [x] Replaced "onclick" with "click" and tested
