### ISSUE TITLE
USER STORY: ERROR HANDLERS

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/restaurant#26]
As a **Site Owner** I can **display pages to show errors to users** so that **they stay on my site**

## ACCEPTANCE CRITERIA 

- Have Errors lead to User designed pages
- Have Errors explained in HTML
- Have Errors Styled 
- Have Errors Tested for response

## TASKS

- [x] CREATE ERROR HANDLER FOR 403 Forbidden error
- [x] CREATE ERROR HANDLER FOR 404 not found error
- [x] CREATE ERROR HANDLER FOR 500 Internal Server Error
- [x] Create HTML for Error Handlers
- [x] Create CSS for Error Handlers
- [x] Create URLS for Error Handlers
- [x] Create TESTS to Test Errors and Response
