### ISSUE TITLE
USER STORIES : PREVENT "DOUBLE BOOKINGS"

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/restaurant#29]
As a **Site Owner** I want the site to **prevent users booking more than one slot a day** as this would **prevent duplicate bookings made in error** and **prevent users bypassing the party size limit for bookings**.

## ACCEPTANCE CRITERIA 

- User unable to make a booking if they have one already on that date
- User Shown an error message as to why the booking was not submitted

## TASKS

- [x] Check if user has preexisting booking on date of new booking
- [x] Prevent submission of booking if one exists for that date
- [x] Display an error message to the user as to why booking not submitted
- [x] Test errors display correctly and Booking not logged in Database
