### ISSUE TITLE
ENHANCEMENTS

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/restaurant#32]
- [ ] DISPLAY ERROR MESSAGE FOR NAME AND EMAIL NOT COMPLETE
- [ ] DISPLAY MESSAGE IF BOOKINGS MORE THAN 6 TO RING
- [ ] ALLOW ADMIN TO CREATE BOOKINGS MORE THAN 6
- [ ] FORGOT PASSWORD LINK
- [ ] EMAIL VERIFICATION OF BOOKING
- [ ] REMEMBER ME BUTTON AT LOGIN
- [ ] REMOVE MODAL TO CONFIRM BOOKING UNLESS BOOKING IS VALID
- [ ] IF USER ALREADY HAS BOOKINGS BRING THEM TO THEIR BOOKINGS
- [ ] DISPLAY BOOKINGS BY DATE OF BOOKING  (SOONEST FIRST)
- [ ] IF USER TRIES TO EDIT BOOKING FOR SAME TIME AS EXISTING BOOKING, NOTIFY THEM?
- [ ] PREVENT DOUBLE BOOKINGS!!!
- 

As a **role** I can **capability** so that **received benefit**

## ACCEPTANCE CRITERIA 

-
-
-

## TASKS

- [ ] task 1
- [ ] task 2
- [ ] task 3
