### ISSUE TITLE
BUG: DOUBLE BOOKING ON EDITS

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/restaurant#33]
## BUG 

- USER able to EDIT pre-existing Bookings to create Double Bookings

## TASKS

- [x] Test why existing Bookings can be edited to create duplicate bookings
- [x] Edit resubmission of edited bookings so they can't create Duplicate bookings
- [x] Ensure Edited bookings are allowed to be submitted if date corresponds to their existing booking
       - As then it's not a duplicate, just a change of details
- [x] Ensure Error Messages displayed correctly
- [x] Test Resubmitted form logged
- [x] Allow user to edit booking and still keep the original date once changed
