### ISSUE TITLE
ENHANCEMENT: CREATE STAFF VIEWS FOR BOOKINGS

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/restaurant#35]
As a **role** I can **capability** so that **received benefit**

## ACCEPTANCE CRITERIA 

-
-
-

## TASKS

- [ ] create staff group in admin panel
- [ ] give staff permissions
- [ ] create views and html for bookings for users with staff permissions
